spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    username: postgres
    password: lab5
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        ddl-auto: none
  flyway:
    enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: example@gmail.com
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true